CREATE TABLE IF NOT EXISTS users (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name varchar,
email varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS request (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
description varchar NOT NULL,
requestor_id BIGINT REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS items (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name varchar NOT NULL,
description varchar NOT NULL,
available boolean,
owner_id BIGINT REFERENCES users (id),
request_id BIGINT REFERENCES request (id)
);

CREATE TABLE IF NOT EXISTS bookings (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
item_id BIGINT REFERENCES items (id) ON DELETE CASCADE,
booker_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
status varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
text varchar NOT NULL,
item_id BIGINT REFERENCES items (id) ON DELETE CASCADE,
author_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
